/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./app/**/*.{vue,js,ts}",
    "./components/**/*.{vue,js,ts}",
    "./layouts/**/*.{vue,js,ts}",
    "./pages/**/*.{vue,js,ts}",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
    "presets/**/*.{js,vue,ts}",
  ],
  theme: {
    extend: {
      colors: {
        amarilloIENM: "#fbdc00",
        verdeIENM: "#f4b233",
        verdeOscIENM: "#c38e28",
        rojoIENM: "#c86a2b",
        azulClaroIENM: "#007cbb",
        azulIENM: "#0063a6",
        primary: "rgb(var(--primary))",
        "primary-inverse": "rgb(var(--primary-inverse))",
        "primary-hover": "rgb(var(--primary-hover))",
        "primary-active-color": "rgb(var(--primary-active-color))",

        "primary-highlight":
          "rgb(var(--primary)/var(--primary-highlight-opacity))",
        "primary-highlight-inverse": "rgb(var(--primary-highlight-inverse))",
        "primary-highlight-hover":
          "rgb(var(--primary)/var(--primary-highlight-hover-opacity))",

        "primary-50": "rgb(var(--primary-50))",
        "primary-100": "rgb(var(--primary-100))",
        "primary-200": "rgb(var(--primary-200))",
        "primary-300": "rgb(var(--primary-300))",
        "primary-400": "rgb(var(--primary-400))",
        "primary-500": "rgb(var(--primary-500))",
        "primary-600": "rgb(var(--primary-600))",
        "primary-700": "rgb(var(--primary-700))",
        "primary-800": "rgb(var(--primary-800))",
        "primary-900": "rgb(var(--primary-900))",
        "primary-950": "rgb(var(--primary-950))",

        "surface-0": "rgb(var(--surface-0))",
        "surface-50": "rgb(var(--surface-50))",
        "surface-100": "rgb(var(--surface-100))",
        "surface-200": "rgb(var(--surface-200))",
        "surface-300": "rgb(var(--surface-300))",
        "surface-400": "rgb(var(--surface-400))",
        "surface-500": "rgb(var(--surface-500))",
        "surface-600": "rgb(var(--surface-600))",
        "surface-700": "rgb(var(--surface-700))",
        "surface-800": "rgb(var(--surface-800))",
        "surface-900": "rgb(var(--surface-900))",
        "surface-950": "rgb(var(--surface-950))",
      },
      fontFamily: {
        sans: ["Verdana", "Geneva", "Tahoma", "sans-serif"],
        verdana: ["Verdana", "Geneva", "Tahoma", "sans-serif"],
        // 'manrope-b': ['Manrope-Bold'],
        // 'manrope-extrab': ['Manrope-ExtraBold'],
        // 'manrope-extral': ['Manrope-ExtraLight'],
        // 'manrope-l': ['Manrope-Light'],
        // 'manrope-r': ['Manrope-Regular'],
        // 'verdana-r': ['Verdana-Regular'],
        // 'verdana-b': ['Verdana-Bold'],
        // 'verdana-i': ['Verdana-Italic'],
        // 'verdana-b-i': ['Verdana-Bold-Italic'],
        // 'futura-m': ['Futura-Medium'],
        // 'futura-l': ['Futura-Light'],
        // 'futura-l-o': ['Futura-Light-Oblique'],
        // 'futura-b': ['Futura-Bold'],
        // 'futura-b-o': ['Futura-Bold-Oblique'],
      },
    },
  },
  plugins: [],
};
